<?php

/**
 * This is the model base class for the table "tbl_letters".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Letters".
 *
 * Columns in table "tbl_letters" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $letter_created
 * @property integer $signed_date
 * @property integer $signed_recieve
 * @property string $decided_assigned
 * @property string $verification_period
 * @property string $content
 * @property string $staff_assigned
 *
 */
abstract class BaseLetters extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_letters';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Letters|Letters', $n);
	}

	public static function representingColumn() {
		return 'letter_created';
	}

	public function rules() {
		return array(
			array('signed_date, signed_recieve', 'numerical', 'integerOnly'=>true),
			array('letter_created, decided_assigned, verification_period, content, staff_assigned', 'safe'),
			array('letter_created, signed_date, signed_recieve, decided_assigned, verification_period, content, staff_assigned', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, letter_created, signed_date, signed_recieve, decided_assigned, verification_period, content, staff_assigned', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'letter_created' => Yii::t('app', 'Letter Created'),
			'signed_date' => Yii::t('app', 'Signed Date'),
			'signed_recieve' => Yii::t('app', 'Signed Recieve'),
			'decided_assigned' => Yii::t('app', 'Decided Assigned'),
			'verification_period' => Yii::t('app', 'Verification Period'),
			'content' => Yii::t('app', 'Content'),
			'staff_assigned' => Yii::t('app', 'Staff Assigned'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('letter_created', $this->letter_created, true);
		$criteria->compare('signed_date', $this->signed_date);
		$criteria->compare('signed_recieve', $this->signed_recieve);
		$criteria->compare('decided_assigned', $this->decided_assigned, true);
		$criteria->compare('verification_period', $this->verification_period, true);
		$criteria->compare('content', $this->content, true);
		$criteria->compare('staff_assigned', $this->staff_assigned, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}