<?php

/**
 * This is the model base class for the table "tbl_cases".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Cases".
 *
 * Columns in table "tbl_cases" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property integer $date_prosecution
 * @property string $accused
 * @property string $detention_period
 * @property string $investigator
 * @property string $investigation_period
 *
 */
abstract class BaseCases extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_cases';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Cases|Cases', $n);
	}

	public static function representingColumn() {
		return 'accused';
	}

	public function rules() {
		return array(
			array('date_prosecution', 'numerical', 'integerOnly'=>true),
			array('accused, detention_period, investigator, investigation_period', 'safe'),
			array('date_prosecution, accused, detention_period, investigator, investigation_period', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, date_prosecution, accused, detention_period, investigator, investigation_period', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'date_prosecution' => Yii::t('app', 'Date Prosecution'),
			'accused' => Yii::t('app', 'Accused'),
			'detention_period' => Yii::t('app', 'Detention Period'),
			'investigator' => Yii::t('app', 'Investigator'),
			'investigation_period' => Yii::t('app', 'Investigation Period'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('date_prosecution', $this->date_prosecution);
		$criteria->compare('accused', $this->accused, true);
		$criteria->compare('detention_period', $this->detention_period, true);
		$criteria->compare('investigator', $this->investigator, true);
		$criteria->compare('investigation_period', $this->investigation_period, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}